services:
  - type: web
    name: prisoners-dilemma-lab
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn pages.app:server --bind 0.0.0.0:$PORT

